spring:
  datasource:
    url:  jdbc:h2:tcp://localhost/~/crm-h2
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: waonderboy@gmail.com
    password: npdgsoyndqlfftfm
    properties:
      mail.smtp.auth: true
      mail.smtp.timeout: 5000
      mail.smtp.starttls.enable: true

logging:
  level:
    #org.hibernate.SQL: debug
    org.hibernate.type: trace

jwt:
  header: Authorization
  token-validity-in-seconds: 9900000
  refresh-validity-in-seconds: 99000000